# **NLP EXAMPLE WITH GOOGLE-COLAB**

The
dataset that will be analyse contains 65K news headlines obtained from HuffPost. Each article is categorized,
and a short description is included along with a link to the original text. 
The objective is to develop a classification model to
predict the category of similar news articles. 

### **Tips for Collaborate**

https://medium.com/lean-in-women-in-tech-india/google-colab-the-beginners-guide-5ad3b417dfa

https://research.google.com/colaboratory/local-runtimes.html

### **Conda magic**
https://ipython.readthedocs.io/en/stable/interactive/magics.html


### **See available packages**

In [ ]:
## see all the installed packages
#!python -m pip install freeze
#import freeze
#from pip._internal.operations.freeze import freeze
#for requirement in freeze(local_only=True):
#    print(requirement)

absl-py==0.8.0
alabaster==0.7.12
albumentations==0.1.12
altair==3.2.0
astor==0.8.0
astropy==3.0.5
atari-py==0.1.15
atomicwrites==1.3.0
attrs==19.1.0
audioread==2.1.8
autograd==1.3
Babel==2.7.0
backcall==0.1.0
backports.tempfile==1.0
backports.weakref==1.0.post1
beautifulsoup4==4.6.3
bert-tensorflow==1.0.1
bleach==3.1.0
blis==0.2.4
bokeh==1.0.4
boto==2.49.0
boto3==1.9.224
botocore==1.12.224
Bottleneck==1.2.1
branca==0.3.1
bs4==0.0.1
bz2file==0.98
cachetools==3.1.1
certifi==2019.6.16
cffi==1.12.3
chainer==5.4.0
chardet==3.0.4
Click==7.0
cloudpickle==0.6.1
cmake==3.12.0
community==1.0.0b1
contextlib2==0.5.5
convertdate==2.1.3
coverage==3.7.1
coveralls==0.5
crcmod==1.7
cvxopt==1.2.3
cvxpy==1.0.25
cycler==0.10.0
cymem==2.0.2
Cython==0.29.13
daft==0.0.4
dask==1.1.5
dataclasses==0.6
datascience==0.10.6
decorator==4.4.0
defusedxml==0.6.0
descartes==1.1.0
dill==0.3.0
distributed==1.25.3
Django==2.2.5
dlib==19.16.0
dm-sonnet==1.35
docopt==0.6.2
docutils==0.15.2
dopamine-rl==1.0.5
easydict==1.9
e

# Install packages

In [ ]:
#to save the packages in my google drive
#from google.colab import drive
#drive.mount('/content/drive')
#pip freeze --local > /content/drive/My\ Drive/Colab\ Notebooks/NLP/colab_installed.txt

In [ ]:
#import os
#os.getcwd() # pwd

'/content'

In [ ]:
#with open('/content/drive/My Drive/Colab Notebooks/NLP/foo.py', 'w') as f:
#  f.write('import numpy')
#!cat /content/drive/My\ Drive/Colab\ Notebooks/NLP/foo.py

#!cat /content/drive/My\ Drive/Colab\ Notebooks/NLP/module.py


import numpy

In [ ]:
#!python /content/drive/My\ Drive/Colab\ Notebooks/NLP/foo.py

## **INSTALL PACKAGES**

In [5]:
# Install packages (is there possible to ceate enviroments in googgle collaborate?)

!python -m pip install numpy
!python -m pip install tensorflow
!python -m pip install tensorboard
# install the requirements
!pip install tensorflow-gpu
!pip install bert-tensorflow
!pip install spacy
'''

'''
!python -m pip install numpy #==1.16.5
!python -m pip install tensorflow==1.14.0 #1.12.0
!python -m pip install tensorboard==1.14.0
# install the requirements
!pip install tensorflow-gpu==1.14.0
!pip install bert-tensorflow==1.0.1
!pip install spacy==2.1.8


!python -m spacy download en
#BERT-Base, Uncased: 12-layer, 768-hidden, 12-heads, 110M parameters
!wget https://storage.googleapis.com/bert_models/2018_10_18/uncased_L-12_H-768_A-12.zip
!unzip uncased_L-12_H-768_A-12.zip -d bert_models
!rm uncased_L-12_H-768_A-12.zip



     |████████████████████████████████| 380.8MB 56kB/s 
     |████████████████████████████████| 450kB 36.8MB/s 
     |████████████████████████████████| 3.8MB 36.8MB/s 
ERROR: tensorflow 1.15.0rc3 has requirement tensorboard<1.16.0,>=1.15.0, but you'll have tensorboard 2.0.0 which is incompatible.
ERROR: tensorflow 1.15.0rc3 has requirement tensorflow-estimator==1.15.1, but you'll have tensorflow-estimator 2.0.0 which is incompatible.
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0


     |████████████████████████████████| 71kB 8.2MB/s 
     |████████████████████████████████| 109.2MB 45.8MB/s 
     |████████████████████████████████| 491kB 54.4MB/s 
     |████████████████████████████████| 3.2MB 46.3MB/s 
ERROR: tensorflow-gpu 2.0.0 has requirement tensorboard<2.1.0,>=2.0.0, but you'll have tensorboard 1.14.0 which is incompatible.
ERROR: tensorflow-gpu 2.0.0 has requirement tensorflow-estimator<2.1.0,>=2.0.0, but you'll have tensorflow-estimator 1.14.0 which is incompatible.
  Found existing installation: tensorflow-estimator 2.0.0
    Uninstalling tensorflow-estimator-2.0.0:
      Successfully uninstalled tensorflow-estimator-2.0.0
  Found existing installation: tensorboard 2.0.0
    Uninstalling tensorboard-2.0.0:
      Successfully uninstalled tensorboard-2.0.0
  Found existing installation: tensorflow 1.15.0rc3
    Uninstalling tensorflow-1.15.0rc3:
      Successfully uninstalled tensorflow-1.15.0rc3
     |████████████████████████████████| 377.0MB 33kB/s 
  Foun

✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_sm')
✔ Linking successful
/usr/local/lib/python3.6/dist-packages/en_core_web_sm -->
/usr/local/lib/python3.6/dist-packages/spacy/data/en
You can now load the model via spacy.load('en')
--2019-10-18 12:32:04--  https://storage.googleapis.com/bert_models/2018_10_18/uncased_L-12_H-768_A-12.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 108.177.126.128, 2a00:1450:4013:c00::80
Connecting to storage.googleapis.com (storage.googleapis.com)|108.177.126.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 407727028 (389M) [application/zip]
Saving to: ‘uncased_L-12_H-768_A-12.zip’

uncased_L-12_H-768_ 100%[===================>] 388.84M  77.8MB/s    in 5.0s    

2019-10-18 12:32:09 (77.8 MB/s) - ‘uncased_L-12_H-768_A-12.zip’ saved [407727028/407727028]

Archive:  uncased_L-12_H-768_A-12.zip
   creating: bert_models/uncased_L-12_H-768_A-12/
  inflating: bert_mode

In [3]:
##install
'''
nb_path = '/content/drive/My\ Drive/Colab\ Notebooks/NLP/'
os.symlink('/content/drive/My\ Drive/Colab\ Notebooks/NLP/', nb_path)
sys.path.insert(0, nb_path)  # or append(nb_path)
# Install only once. Tomorrow, you can skip this.
!pip install --target=$nb_path jdc
'''

"\nnb_path = '/content/drive/My\\ Drive/Colab\\ Notebooks/NLP/'\nos.symlink('/content/drive/My\\ Drive/Colab\\ Notebooks/NLP/', nb_path)\nsys.path.insert(0, nb_path)  # or append(nb_path)\n# Install only once. Tomorrow, you can skip this.\n!pip install --target=$nb_path jdc\n"

# Load Data

In [ ]:
import os
import pandas as pd
import numpy as np
import re
import string

import tensorflow as tf

from bert import tokenization
from bert import modeling

from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import precision_score, recall_score, f1_score, \
                            roc_auc_score, accuracy_score

from sklearn.preprocessing import LabelEncoder
    
from tqdm import tqdm
import spacy

tqdm.pandas()

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [8]:
#load modules from text
#!python -m pip --upgrade --force-reinstall `cat/content/drive/My\ Drive/Colab\ Notebooks/NLP/`

#!python '/content/drive/My\ Drive/Colab\ Notebooks/NLP/colab_installed.txt' install

python3: can't open file '/content/drive/My\ Drive/Colab\ Notebooks/NLP/colab_installed.txt': [Errno 2] No such file or directory


In [ ]:
data_df = pd.read_json('/content/drive/My Drive/Colab Notebooks/NLP/data/News_category_train.json')
headlines = data_df['headline'].values.tolist()
short_descriptions = data_df['short_description'].values.tolist()
categories = data_df['category']

The data contains the following columns:
> **authors** - ...<br>
> **category** - ...<br>
> **headline** - ...<br>
> **link** - ...<br>
> **short_description** - ...<br>

In [10]:
data_df.tail()

authors  ...                                  short_description
64995  Suzanne Perryman, Contributor\nBlogger at Spec...  ...  I never imagined that she would thank me. That...
64996  Daniel B. Peters, Ph.D., Contributor\nCo-Found...  ...  Living on the spectrum comes with daily challe...
64997  Kim Simon, Contributor\nWriter. Mother. Wife. ...  ...  One thing's for sure in the dead of the night,...
64998  Jim Higley, Contributor\nJim's a dad who happe...  ...  I've had the good fortune of giving each of my...
64999  Sara Esther Crispe, Contributor\nCo-Director o...  ...  My children needed a more patient and focused ...

[5 rows x 5 columns]

In [11]:
data_df.head()

authors  ...                                  short_description
0                                    Priscilla Frank  ...  And it's all a delicious homage to a 1950s art...
1  Jocelyn Jeffery, ContributorFounder/Editor-In-...  ...  For Smith and Emin, the body is in perpetual m...
2    Danny Groner, Contributor\nFreelance Journalist  ...  The Internet has unquestionably reformed how w...
3                                    Priscilla Frank  ...                                                   
4            Larissa Bates, Contributor\nContributor  ...  Simple Men, 2013, oil on canvas, 42 by 36 inch...

[5 rows x 5 columns]

## **Treat data**

In [12]:
## dimensions of the data
## check for missing values
data_df.isnull().sum()
# if something is null (text is difficult to complete)
#df.dropna(inplace=True)
#len(df)

authors              0
category             0
headline             0
link                 0
short_description    0
dtype: int64

## Eliminate White strings:
Ex: '      ': too many spaces without characters

In [13]:
blanks = []  # start with an empty list

for i,lb,rv in data_df[['authors', 'category']].itertuples():  # iterate over the DataFrame
    if type(rv)==str:            # avoid NaN values
        if rv.isspace():         # test 'review' for whitespace
            blanks.append(i)     # add matching index numbers to the list
        
print(len(blanks), 'blanks: ', blanks)

0 blanks:  []


### For some reason for headline, I can not count white strings

In [18]:
blanks = []  # start with an empty list

for i,lb,rv in data_df[['link', 'headline']].itertuples():  # iterate over the DataFrame
    if type(rv)==str:            # avoid NaN values
        if rv.isspace():         # test 'review' for whitespace
            blanks.append(i)     # add matching index numbers to the list
        
print(len(blanks), 'blanks: ', blanks)

0 blanks:  []


In [19]:
blanks = []  # start with an empty list

for i,lb,rv in data_df[['link',	'short_description']].itertuples():  # iterate over the DataFrame
    if type(rv)==str:            # avoid NaN values
        if rv.isspace():         # test 'review' for whitespace
            blanks.append(i)     # add matching index numbers to the list
        
print(len(blanks), 'blanks: ', blanks)

0 blanks:  []


(If there are blanks) Next we'll pass our list of index numbers to the **.drop()** method, and set `inplace=True` to make the change permanent.

In [20]:
data_df.drop(blanks, inplace=True)

len(data_df)

65000

In [21]:
data_df.columns

Index(['authors', 'category', 'headline', 'link', 'short_description'], dtype='object')

## **Eliminate undesirable characters**

In [ ]:
def standardize_text(df, text_field):
    df[text_field] = df[text_field].str.replace(r"http\S+", "")
    df[text_field] = df[text_field].str.replace(r"http", "")
    df[text_field] = df[text_field].str.replace(r"@\S+", "")
    df[text_field] = df[text_field].str.replace(r"\n", "")
    df[text_field] = df[text_field].str.replace(r"[^A-Za-z0-9(),!?@\'\`\"\_\n]", " ")
    df[text_field] = df[text_field].str.replace(r"@", "at")
    df[text_field] = df[text_field].str.lower()
    return df

data_df_1 = standardize_text(data_df, "headline")
data_df_1 = standardize_text(data_df_1, "authors")
data_df = standardize_text(data_df_1, "short_description")

In [23]:
data_df.head()

authors  ...                                  short_description
0                                    priscilla frank  ...  and it's all a delicious homage to a 1950s art...
1  jocelyn jeffery, contributorfounder editor in ...  ...  for smith and emin, the body is in perpetual m...
2      danny groner, contributorfreelance journalist  ...  the internet has unquestionably reformed how w...
3                                    priscilla frank  ...                                                   
4              larissa bates, contributorcontributor  ...  simple men, 2013, oil on canvas, 42 by 36 inch...

[5 rows x 5 columns]

In [24]:
data_df.groupby("category")['link'].count()

category
A     2000
B     2000
C     2000
D    10000
E     5000
F    10000
G    20000
H     2000
I     2000
J    10000
Name: link, dtype: int64

## Take a quick look at the `label` column:

In [25]:
data_df['category'].value_counts()

G    20000
D    10000
F    10000
J    10000
E     5000
A     2000
I     2000
H     2000
C     2000
B     2000
Name: category, dtype: int64

In [26]:
data_df['category'].value_counts()/len(data_df)

G    0.307692
D    0.153846
F    0.153846
J    0.153846
E    0.076923
A    0.030769
I    0.030769
H    0.030769
C    0.030769
B    0.030769
Name: category, dtype: float64

## Split the data into train & test sets:

In [ ]:
from sklearn.model_selection import train_test_split

X = data_df['headline'] #.drop(columns = 'category') # with link we got an error
y = data_df['category']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, stratify = y,random_state=42)

In [28]:
y_train.value_counts()/len(data_df)

G    0.206154
D    0.103077
F    0.103077
J    0.103077
E    0.051538
A    0.020615
I    0.020615
H    0.020615
C    0.020615
B    0.020615
Name: category, dtype: float64

In [29]:
y_test.value_counts()/len(data_df)

G    0.101538
F    0.050769
D    0.050769
J    0.050769
E    0.025385
C    0.010154
B    0.010154
A    0.010154
I    0.010154
H    0.010154
Name: category, dtype: float64

## **TFIDF Bag of Words**
Let's try a slightly more subtle approach. On top of our bag of words model, we use a TF-IDF (Term Frequency, Inverse Document Frequency) which means weighing words by how frequent they are in our dataset, discounting words that are too frequent, as they just add to the noise.

## Build pipelines to vectorize the data, then train and fit a model

We'll develop a selection of pipelines, each with a different model.


In [ ]:

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

# Naïve Bayes:
text_clf_nb = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', MultinomialNB()),
])

# Linear SVC:
text_clf_lsvc = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', LinearSVC()),
])

## Feed the training data through the first pipeline
We'll run naïve Bayes first

In [32]:
text_clf_nb.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('clf',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [ ]:
#Tfid
def tfidf(data):
    tfidf_vectorizer = TfidfVectorizer()

    train = tfidf_vectorizer.fit_transform(data)

    return train, tfidf_vectorizer


## Run predictions and analyze the results (naïve Bayes)

In [ ]:
# Form a prediction set
predictions = text_clf_nb.predict(X_test)

In [35]:
# Report the confusion matrix
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[   5    0    0  168    0  135  273    0    0   79]
 [   0    0    0   22    2   72  498    0    0   66]
 [   0    0   27  101    0    8  476    0    0   48]
 [   0    0    0 1703   11  147 1221    0    0  218]
 [   0    0    0  128  629  217  375    0    0  301]
 [   0    0    0   73    3 2752  302    0    0  170]
 [   0    0    0   70    0   13 6468    0    0   49]
 [   0    0    2   23    0    7  608    1    0   19]
 [   0    0    1   70    4   74  396    0    1  114]
 [   0    0    0   84    6  106  538    0    0 2566]]


In [36]:
# Print a classification report
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

           A       1.00      0.01      0.02       660
           B       0.00      0.00      0.00       660
           C       0.90      0.04      0.08       660
           D       0.70      0.52      0.59      3300
           E       0.96      0.38      0.55      1650
           F       0.78      0.83      0.81      3300
           G       0.58      0.98      0.73      6600
           H       1.00      0.00      0.00       660
           I       1.00      0.00      0.00       660
           J       0.71      0.78      0.74      3300

    accuracy                           0.66     21450
   macro avg       0.76      0.35      0.35     21450
weighted avg       0.71      0.66      0.60     21450



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [37]:
# Print the overall accuracy
print(metrics.accuracy_score(y_test,predictions))

0.6597668997668997


## Feed the training data through the second pipeline
Next we'll run Linear SVC

In [38]:
text_clf_lsvc.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('clf',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept=True, intercept_scaling=1,
               

In [ ]:
# Form a prediction set
predictions = text_clf_lsvc.predict(X_test)

In [40]:
# Report the confusion matrix
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[ 288   12    2   99    5   95   76    8   15   60]
 [   6  339   13   32    9   38  122   21   30   50]
 [   1    7  358   73    4   11  105    6   52   43]
 [  42   12   53 2316   46  138  431   13   24  225]
 [   9    5    4   46 1344   71   40    2   10  119]
 [  25   16    4   91   42 2864  102    6   15  135]
 [  16   63   52  300   22   58 5826   98   18  147]
 [  10   18   17   52    1   11  224  289   10   28]
 [  11   32   47   54   11   64   92    8  264   77]
 [  20   20   11  135   64  133  147   10   23 2737]]


In [41]:
# Print a classification report
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

           A       0.67      0.44      0.53       660
           B       0.65      0.51      0.57       660
           C       0.64      0.54      0.59       660
           D       0.72      0.70      0.71      3300
           E       0.87      0.81      0.84      1650
           F       0.82      0.87      0.84      3300
           G       0.81      0.88      0.85      6600
           H       0.63      0.44      0.52       660
           I       0.57      0.40      0.47       660
           J       0.76      0.83      0.79      3300

    accuracy                           0.78     21450
   macro avg       0.71      0.64      0.67     21450
weighted avg       0.77      0.78      0.77     21450



In [42]:
# Print the overall accuracy
print(metrics.accuracy_score(y_test,predictions))

0.7750582750582751


## Advanced Topic - Adding Stopwords to CountVectorizer
By default, **CountVectorizer** and **TfidfVectorizer** do *not* filter stopwords. However, they offer some optional settings, including passing in your own stopword list.
<div class="alert alert-info" style="margin: 20px">CAUTION: There are some [known issues](http://aclweb.org/anthology/W18-2502) using Scikit-learn's built-in stopwords list. Some words that are filtered may in fact aid in classification. In this section we'll pass in our own stopword list, so that we know exactly what's being filtered.</div>

The [CountVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) class accepts the following arguments:
> *CountVectorizer(input='content', encoding='utf-8', decode_error='strict', strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, **stop_words=None**, token_pattern='(?u)\b\w\w+\b', ngram_range=(1, 1), analyzer='word', max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=<class 'numpy.int64'>)*

[TfidVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html) supports the same arguments and more. Under *stop_words* we have the following options:
> stop_words : *string {'english'}, list, or None (default)*

That is, we can run `TfidVectorizer(stop_words='english')` to accept scikit-learn's built-in list,<br>
or `TfidVectorizer(stop_words=[a, and, the])` to filter these three words. In practice we would assign our list to a variable and pass that in instead.

Scikit-learn's built-in list contains 318 stopwords:
> <pre>from sklearn.feature_extraction import text
> print(text.ENGLISH_STOP_WORDS)</pre>
['a', 'about', 'above', 'across', 'after', 'afterwards', 'again', 'against', 'all', 'almost', 'alone', 'along', 'already', 'also', 'although', 'always', 'am', 'among', 'amongst', 'amoungst', 'amount', 'an', 'and', 'another', 'any', 'anyhow', 'anyone', 'anything', 'anyway', 'anywhere', 'are', 'around', 'as', 'at', 'back', 'be', 'became', 'because', 'become', 'becomes', 'becoming', 'been', 'before', 'beforehand', 'behind', 'being', 'below', 'beside', 'besides', 'between', 'beyond', 'bill', 'both', 'bottom', 'but', 'by', 'call', 'can', 'cannot', 'cant', 'co', 'con', 'could', 'couldnt', 'cry', 'de', 'describe', 'detail', 'do', 'done', 'down', 'due', 'during', 'each', 'eg', 'eight', 'either', 'eleven', 'else', 'elsewhere', 'empty', 'enough', 'etc', 'even', 'ever', 'every', 'everyone', 'everything', 'everywhere', 'except', 'few', 'fifteen', 'fifty', 'fill', 'find', 'fire', 'first', 'five', 'for', 'former', 'formerly', 'forty', 'found', 'four', 'from', 'front', 'full', 'further', 'get', 'give', 'go', 'had', 'has', 'hasnt', 'have', 'he', 'hence', 'her', 'here', 'hereafter', 'hereby', 'herein', 'hereupon', 'hers', 'herself', 'him', 'himself', 'his', 'how', 'however', 'hundred', 'i', 'ie', 'if', 'in', 'inc', 'indeed', 'interest', 'into', 'is', 'it', 'its', 'itself', 'keep', 'last', 'latter', 'latterly', 'least', 'less', 'ltd', 'made', 'many', 'may', 'me', 'meanwhile', 'might', 'mill', 'mine', 'more', 'moreover', 'most', 'mostly', 'move', 'much', 'must', 'my', 'myself', 'name', 'namely', 'neither', 'never', 'nevertheless', 'next', 'nine', 'no', 'nobody', 'none', 'noone', 'nor', 'not', 'nothing', 'now', 'nowhere', 'of', 'off', 'often', 'on', 'once', 'one', 'only', 'onto', 'or', 'other', 'others', 'otherwise', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 'part', 'per', 'perhaps', 'please', 'put', 'rather', 're', 'same', 'see', 'seem', 'seemed', 'seeming', 'seems', 'serious', 'several', 'she', 'should', 'show', 'side', 'since', 'sincere', 'six', 'sixty', 'so', 'some', 'somehow', 'someone', 'something', 'sometime', 'sometimes', 'somewhere', 'still', 'such', 'system', 'take', 'ten', 'than', 'that', 'the', 'their', 'them', 'themselves', 'then', 'thence', 'there', 'thereafter', 'thereby', 'therefore', 'therein', 'thereupon', 'these', 'they', 'thick', 'thin', 'third', 'this', 'those', 'though', 'three', 'through', 'throughout', 'thru', 'thus', 'to', 'together', 'too', 'top', 'toward', 'towards', 'twelve', 'twenty', 'two', 'un', 'under', 'until', 'up', 'upon', 'us', 'very', 'via', 'was', 'we', 'well', 'were', 'what', 'whatever', 'when', 'whence', 'whenever', 'where', 'whereafter', 'whereas', 'whereby', 'wherein', 'whereupon', 'wherever', 'whether', 'which', 'while', 'whither', 'who', 'whoever', 'whole', 'whom', 'whose', 'why', 'will', 'with', 'within', 'without', 'would', 'yet', 'you', 'your', 'yours', 'yourself', 'yourselves']

However, there are words in this list that may influence a classification of movie reviews. With this in mind, let's trim the list to just 60 words:

In [ ]:
stopwords = ['a', 'about', 'an', 'and', 'are', 'as', 'at', 'be', 'been', 'but', 'by', 'can', \
             'even', 'ever', 'for', 'from', 'get', 'had', 'has', 'have', 'he', 'her', 'hers', 'his', \
             'how', 'i', 'if', 'in', 'into', 'is', 'it', 'its', 'just', 'me', 'my', 'of', 'on', 'or', \
             'see', 'seen', 'she', 'so', 'than', 'that', 'the', 'their', 'there', 'they', 'this', \
             'to', 'was', 'we', 'were', 'what', 'when', 'which', 'who', 'will', 'with', 'you']

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn import metrics

In [46]:
# RUN THIS CELL TO ADD STOPWORDS TO THE LINEAR SVC PIPELINE:
text_clf_lsvc2 = Pipeline([('tfidf', TfidfVectorizer(stop_words=stopwords)),
                     ('clf', LinearSVC()),
])
text_clf_lsvc2.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=['a', 'about', 'an', 'and', 'are',
                                             'as', 'at', 'be', 'been', 'but',...
                                             'how', 'i', 'if', 'in', 'into',
                                             'is', ...],
                                 strip_accents=None, sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer

In [47]:
predictions = text_clf_lsvc2.predict(X_test)
print(metrics.confusion_matrix(y_test,predictions))

[[ 290   14    2   91    4   98   79   10   15   57]
 [   5  328   10   31   11   38  126   21   34   56]
 [   0    7  350   77    4   12  108    9   50   43]
 [  47   13   54 2309   48  147  434   13   17  218]
 [   9    6    5   47 1349   66   42    1   12  113]
 [  23   19    4   90   41 2860  100    6   18  139]
 [  15   64   52  301   25   55 5813  100   23  152]
 [  11   22   17   50    1   15  218  293    8   25]
 [  11   30   47   51   14   64   92    6  255   90]
 [  20   19   13  132   61  132  158    9   29 2727]]


In [48]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

           A       0.67      0.44      0.53       660
           B       0.63      0.50      0.55       660
           C       0.63      0.53      0.58       660
           D       0.73      0.70      0.71      3300
           E       0.87      0.82      0.84      1650
           F       0.82      0.87      0.84      3300
           G       0.81      0.88      0.84      6600
           H       0.63      0.44      0.52       660
           I       0.55      0.39      0.45       660
           J       0.75      0.83      0.79      3300

    accuracy                           0.77     21450
   macro avg       0.71      0.64      0.67     21450
weighted avg       0.77      0.77      0.77     21450



In [49]:
print(metrics.accuracy_score(y_test,predictions))

0.7726806526806527


Our score didn't change that much. Keep in mind that 2000 movie reviews is a relatively small dataset. The real gain from stripping stopwords is improved processing speed; depending on the size of the corpus, it might save hours.

## GIVE AN EXAMPLE
You can create your own example and give more value to the results...!!!!
Por example: if we are talking about pos/neg reviews: give an example of a positive review and prove it in the model.

## **TOPIC MODELLING**

With the data that we have, see how many categories will fine (unsupervised learning)